CREATE PROCEDURE SALES_SUMMARY
AS
	SELECT 
		O.ORDER_ID, 
		O.CUSTOMER_ID, 
		O.ORDER_DATE, 
		O.STATUS, 
		SUM(P.AMOUNT) OVER (PARTITION BY O.CUSTOMER_ID) AS TOTAL_AMOUNT
	FROM 
		ORDERS AS O 
	INNER JOIN 
		PAYMENTS AS P 
	ON 
		O.ORDER_ID = P.ORDER_ID;
GO;

CREATE PROCEDURE CUSTOMER_SUMMARY
AS
	SELECT C.CUSTOMER_ID, C.NAME, C.EMAIL, C.SIGNUP_DATE, COUNT(O.ORDER_ID) AS TOTAL_ORDERS, SUM(P.AMOUNT) AS TOTAL_SPENT
	FROM CUSTOMERS AS C 
	INNER JOIN ORDERS AS O 
	ON O.CUSTOMER_ID = C.CUSTOMER_ID 
	INNER JOIN PAYMENTS AS P 
	ON P.ORDER_ID = O.ORDER_ID
	GROUP BY C.CUSTOMER_ID, C.NAME, C.EMAIL, C.SIGNUP_DATE
GO;

CREATE PROCEDURE PRODUCT_SUMMARY
AS 
	SELECT DISTINCT P.PRODUCT_ID, P.NAME, P.CATEGORY, SUM(O.QUANTITY) OVER (PARTITION BY P.PRODUCT_ID) as QUANTITY, SUM((A.AMOUNT - (P.PRICE * O.QUANTITY))) OVER (PARTITION BY P.PRODUCT_ID) AS TOTAL_REVENUE
	FROM PRODUCTS AS P
	INNER JOIN ORDER_DETAILS AS O
	ON O.PRODUCT_ID = P.PRODUCT_ID
	INNER JOIN PAYMENTS AS A
	ON A.ORDER_ID = O.ORDER_ID