CREATE DATABASE TARGETDB;
USE TARGETDB;

CREATE TABLE SALESUMMARY (
	ORDER_ID INT NOT NULL UNIQUE,
	CUSTOMER_ID INT NOT NULL,
	ORDER_DATE DATE,
	TOTAL_AMOUNT FLOAT,
	STATUS BIT
);

SELECT * FROM SALESUMMARY
TRUNCATE TABLE SALESUMMARY


CREATE TABLE CUSTOMERSUMMARY (
	CUSTOMER_ID INT NOT NULL UNIQUE,
	NAME VARCHAR(50),
	EMAIL VARCHAR(50),
	SIGNUP_DATE DATE,
	TOTAL_ORDERS INT,
	TOTAL_SPENT FLOAT
);

SELECT * FROM CUSTOMERSUMMARY

CREATE TABLE PRODUCTSUMMARY (
	PRODUCT_ID INT NOT NULL UNIQUE,
	NAME VARCHAR(50),
	CATEGORY VARCHAR(20),
	TOTAL_SOLD FLOAT,
	TOTAL_REVENUE FLOAT 
)

SELECT * FROM PRODUCTSUMMARY
